language: node_js
dist: trusty
node_js:
  - "6.11"
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
cache:
  directories:
    - node_modules
script: npm run travis